### PR TITLE
Adding Rails Panel gem + README documentation about it

### PR DESCRIPTION
**Pull request by Dinuuu**
## Summary
- Adding Rails Panel gem for development environment

### CODE REVIEW

**Comment by hdf1986** [comment]
Maybe would be a good idea to add this gem + plugin here https://github.com/Wolox/tech-guides/blob/master/ruby-on-rails/docs/other/useful-gems.md

**Comment by hdf1986** [comment]
@mishuagopian What do you think? :)

**Comment by Dinuuu** [comment]
Already did @hdf1986  https://github.com/Wolox/tech-guides/pull/58

**Comment by Dinuuu** [comment]
Who can merge this @mishuagopian ?

**Pull request merged**
