### PR TITLE
Added RSpec rubocop gem

### PR DESCRIPTION
**Pull request by alebian**
## Summary

- Added [rubocop-rspec gem](https://github.com/backus/rubocop-rspec)
- Added the [rules](https://github.com/backus/rubocop-rspec/tree/master/lib/rubocop/cop/rspec) that may be excluded in some situations
- Updated rubocop to 0.50.0

### CODE REVIEW

**Comment by hdf1986** [comment]
@alebian The build is failing, i think you might need to run bundle install to update the gemfile.lock file

**Comment by mishuagopian** [comment]
@alebian IMO, it's ok. But fix the build first, please.

**Comment by hdf1986** [comment]
@alebian can we fix the build and merge this?

**Comment by mishuagopian** [comment]
@alebian @hdf1986 are we merging this or should we close it?

**Pull request merged**
